### ISSUE TITLE
2.2.0  pull-batch-size not  take effect

### ISSUE THREAD

**Issue by wonsaign** [apache/rocketmq-spring#400]
在2.2.0版本使用pull模式拉取数据的时候，pull-batch-size 配置了64，但是最大只能到32，每次拉取
我的配置
```yaml
rocketmq:
  name-server: 192.168.9.203:9876
  producer:
    group: sale_group
  consumer:
    group: sale_group
    topic: sale
    selector-type: TAG
    selector-expression: salereord || salereorddetail
    pull-batch-size: 64 # 最多只支持32个大小
```

![image](https://user-images.githubusercontent.com/37646254/138863595-871b62c4-2d24-42b6-b0e5-d2314b560134.png)
