### ISSUE TITLE
使用RocketMQMessageListener订阅多个topic的问题

### ISSUE THREAD

**Issue by MrZbb** [apache/rocketmq-spring#556]
当在一个应用实例使用RocketMQMessageListener订阅多个topic,使用一个消费组的时候例如以下这样
1.@RocketMQMessageListener(topic = "test1",consumerGroup = "consumerGroup")
2.@RocketMQMessageListener(topic = "test2",consumerGroup = "consumerGroup")
会存在严重的消息丢失情况，去服务器查看topic跟的队列信息会出现以下情况，部分队列没有被client绑定造成消息丢失。
![image](https://user-images.githubusercontent.com/31841743/234159423-ca3e3ad0-7de5-4970-9241-9f5fb9bb6ec8.png)
但是看了下官方文档的订阅关系原则如下，一个消费者组跟不同的topic的关系是独立的所有，这边的设计是否产生了矛盾
![image](https://user-images.githubusercontent.com/31841743/234159683-23274d85-1a51-497e-b243-aeca645d1452.png)

**Comment by zangxiyang** [comment]
老哥解决了吗？

**Comment by YshGitHubfcasd** [comment]
您可以通过实现RocketMQPushConsumerLifecycleListener并在prepareStart中为不同consumerGroup的RocketMQMessageListener设置唯一的instanceName来解决此问题。

**Comment by MrZbb** [comment]
> 老哥解决了吗？

最后一个应用实例针对不同topic用的不同consumer-group...只能这样了

**Comment by mufengCc** [comment]
![image](https://github.com/apache/rocketmq-spring/assets/48708389/48dc7408-b3b0-4edb-83cb-1734691b5ad9)

订阅关系不一致。官方文档：https://rocketmq.apache.org/zh/docs/4.x/bestPractice/07subscribe

**Comment by 15521935616** [comment]
> ![image](https://user-images.githubusercontent.com/48708389/265418956-48dc7408-b3b0-4edb-83cb-1734691b5ad9.png)
> 
> 你理解的有问题，代码中明显订阅关系不一致。官方文档：https://rocketmq.apache.org/zh/docs/4.x/bestPractice/07subscribe

确实是订阅关系不一致的问题，那同一个consumer group下多个consumer同时订阅多个topic，老哥有解决思路吗

**Comment by mufengCc** [comment]
![image](https://github.com/apache/rocketmq-spring/assets/48708389/fbba1322-4632-4474-ae45-b7c02612d707)

![image](https://github.com/apache/rocketmq-spring/assets/48708389/6f6ad149-ae98-4dd3-8b5f-8ef1ccf39ed1)


参考上图

**Comment by MrZbb** [comment]
> ![image](https://user-images.githubusercontent.com/48708389/265564613-fbba1322-4632-4474-ae45-b7c02612d707.png)
> 
> ![image](https://user-images.githubusercontent.com/48708389/265564700-6f6ad149-ae98-4dd3-8b5f-8ef1ccf39ed1.png)
> 
> 参考上图

我这边理解从应用维度了，一个应用当一个消费者了。那如果以应用内的一个consumer对象看，那确实我这边理解错了，但是这样子写，会不会存在一个topic需要广播模式消费，一个topic是普通消费就不行了，这种配置方式就不行了

**Comment by liuxuzxx** [comment]
感觉是不是应该配置成数组形式的:

```yaml
rocketmq:
  consumer:
    - topic: topic-a
      consumer-group: topic-a-cg
      pull-bach-size: 100 #默认看着是10
      select-key: "xxxxx"
      message-listener: xxxx.xxxx.xxx.xxx.EmailNotifyMessageListenerConsumer
    - topic: topic-b
      consumer-group: topic-b-cg
    - topic: topic-c
      consumer-group: topic-c-cg
    - ...
```

类似于spring-cloud-stream-message那种配置，支持，多集群，多topic的操作
