### ISSUE TITLE
请问在新版本中怎么配置消息超时、事务回查间隔等属性？

### ISSUE THREAD

**Issue by jevonsnotes** [apache/rocketmq-spring#666]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
使用新版本后，注解中没有消费超时时间，其他配置也不清楚在哪里设置。

- What did you expect to see?
希望可以配置超时时间
- What did you see instead?
经过测试发现在50~60s的sleep后会触发重试
2. Please tell us about your environment:
rocketmq-v5-client-spring 2.3.0
4. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question` | Status: **Answered**

In the newer versions of `rocketmq-spring-boot-starter`, message timeout and transaction rollback interval are configured via:

```yaml
rocketmq:
  producer:
    send-message-timeout: 3000      # milliseconds
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
```

For transaction messages:
```yaml
rocketmq:
  producer:
    transaction-listener:
      check-interval: 60000         # milliseconds (default: 60s)
      check-timeout: 60000          # milliseconds
      max-check-times: 15
```

These properties map to the underlying `DefaultMQProducer` settings.

---
*Automated evaluation by RockteMQ-AI*
